version: '3.0.2'
author: 'Jan Kristinus'
supportpage: www.yakamara.de/tag/xform/
package: xform

navigation:
  title: 'translate:xform'
  perm: xform[]
  subpages:
    overview: {title: 'translate:overview'}
    description: {title: 'translate:description', perm: admin}

requires:
  addons:
    phpmailer:
      min-version: '5.0 alpha2'
